on:
  push:                 
    branches:           
      - main    
name: Build and Deploy  
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master    
      - name: download-basefile
        run: mkdir tmp public && cd tmp && wget https://sda1.net/storage/floorp/basefiles.tar.xz && tar -xf basefiles.tar.xz && rm basefiles.tar.xz 
      - name: Download-floorp-tarball
        run: wget https://github.com/Floorp-Projects/Floorp/releases/download/v10.8.0/floorp-10.8.0.en-US.linux-x86_64.tar.bz2 && tar -jxvf *.tar.bz2 && mv floorp lib/
      - name: compress
        run : tar -Jcf floorp.tar.xz * && mv floorp.tar.xz ../public && cd ..
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0   
        env:                                        
          FTP_SERVER: ${{ secrets.FTP_SERVER }}     
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }} 
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }} 
          LOCAL_DIR: public
          REMOTE_DIR: "/data/floorp-linux/flathub-builds"
      - name: Create PR to Flathub repo
        run: |
          mkdir repo && git clone https://github.com/flathub/one.ablaze.floorp && checkout devel
          cat  one.ablaze.floorp.appdata.xml  | sed -e '21i\        <release version="10.8.0" date="2022-12-18"/>' > one.ablaze.floorp.appdata.xml
          cat one.ablaze.floorp.yml | sed '/^\        sha256:/c\\        sha256: test' > one.ablaze.floorp.yml
          gh push
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
